#!/bin/bash
IFS=$n read -d  -r -a words
declare -A word_count
for word in "${words[@]}"; do
  ((word_count[$word]++))
done
for word in "${!word_count[@]}"; do
  if ((word_count[$word] == 1)); then
    echo "$word"
  fi
done
